// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nareshit.proxy;

import javax.xml.rpc.*;

public interface Hello extends javax.xml.rpc.Service {
    public com.nareshit.proxy.IHelloService getIHelloServicePort() throws ServiceException;
}
