// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nareshit.proxy;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class IHelloService_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements com.nareshit.proxy.IHelloService {
    
    
    
    /*
     *  public constructor
     */
    public IHelloService_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://localhost:2222/HelloService/hello");
    }
    
    
    /*
     *  implementation of sayHello
     */
    public java.lang.String sayHello(java.lang.String string_1)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(sayHello_OPCODE);
            com.nareshit.proxy.IHelloService_sayHello_RequestStruct _myIHelloService_sayHello_RequestStruct =
                new com.nareshit.proxy.IHelloService_sayHello_RequestStruct();
            
            _myIHelloService_sayHello_RequestStruct.setString_1(string_1);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_sayHello_sayHello_QNAME);
            _bodyBlock.setValue(_myIHelloService_sayHello_RequestStruct);
            _bodyBlock.setSerializer(ns1_myIHelloService_sayHello_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.nareshit.proxy.IHelloService_sayHello_ResponseStruct _myIHelloService_sayHello_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myIHelloService_sayHello_ResponseStruct =
                    (com.nareshit.proxy.IHelloService_sayHello_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myIHelloService_sayHello_ResponseStruct =
                    (com.nareshit.proxy.IHelloService_sayHello_ResponseStruct)_responseObj;
            }
            
            return _myIHelloService_sayHello_ResponseStruct.getResult();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case sayHello_OPCODE:
                _deserialize_sayHello(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the sayHello operation.
     */
    private void _deserialize_sayHello(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myIHelloService_sayHello_ResponseStructObj =
            ns1_myIHelloService_sayHello_ResponseStruct_SOAPSerializer.deserialize(ns1_sayHello_sayHelloResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_sayHello_sayHelloResponse_QNAME);
        bodyBlock.setValue(myIHelloService_sayHello_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    public java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected void _preHandlingHook(StreamingSenderState state) throws Exception {
        super._preHandlingHook(state);
    }
    
    
    protected boolean _preRequestSendingHook(StreamingSenderState state) throws Exception {
        boolean bool = false;
        bool = super._preRequestSendingHook(state);
        return bool;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myIHelloService_sayHello_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.nareshit.proxy.IHelloService_sayHello_RequestStruct.class, ns1_sayHello_TYPE_QNAME);
        ns1_myIHelloService_sayHello_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.nareshit.proxy.IHelloService_sayHello_ResponseStruct.class, ns1_sayHelloResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://service.jaxrpcexample.com/wsdl", "IHelloServicePort");
    private static final int sayHello_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_sayHello_sayHello_QNAME = new QName("http://service.jaxrpcexample.com/wsdl", "sayHello");
    private static final javax.xml.namespace.QName ns1_sayHello_TYPE_QNAME = new QName("http://service.jaxrpcexample.com/wsdl", "sayHello");
    private CombinedSerializer ns1_myIHelloService_sayHello_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_sayHello_sayHelloResponse_QNAME = new QName("http://service.jaxrpcexample.com/wsdl", "sayHelloResponse");
    private static final javax.xml.namespace.QName ns1_sayHelloResponse_TYPE_QNAME = new QName("http://service.jaxrpcexample.com/wsdl", "sayHelloResponse");
    private CombinedSerializer ns1_myIHelloService_sayHello_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://service.jaxrpcexample.com/wsdl"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
