// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.wheatherreport.proxy;

import javax.xml.rpc.*;

public interface GeoIPService extends javax.xml.rpc.Service {
    public com.wheatherreport.proxy.GeoIPServiceSoap getGeoIPServiceSoap() throws ServiceException;
}
