// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.wheatherreport.proxy;


public class GeoIP {
    protected int returnCode;
    protected java.lang.String IP;
    protected java.lang.String returnCodeDetails;
    protected java.lang.String countryName;
    protected java.lang.String countryCode;
    
    public GeoIP() {
    }
    
    public GeoIP(int returnCode, java.lang.String IP, java.lang.String returnCodeDetails, java.lang.String countryName, java.lang.String countryCode) {
        this.returnCode = returnCode;
        this.IP = IP;
        this.returnCodeDetails = returnCodeDetails;
        this.countryName = countryName;
        this.countryCode = countryCode;
    }
    
    public int getReturnCode() {
        return returnCode;
    }
    
    public void setReturnCode(int returnCode) {
        this.returnCode = returnCode;
    }
    
    public java.lang.String getIP() {
        return IP;
    }
    
    public void setIP(java.lang.String IP) {
        this.IP = IP;
    }
    
    public java.lang.String getReturnCodeDetails() {
        return returnCodeDetails;
    }
    
    public void setReturnCodeDetails(java.lang.String returnCodeDetails) {
        this.returnCodeDetails = returnCodeDetails;
    }
    
    public java.lang.String getCountryName() {
        return countryName;
    }
    
    public void setCountryName(java.lang.String countryName) {
        this.countryName = countryName;
    }
    
    public java.lang.String getCountryCode() {
        return countryCode;
    }
    
    public void setCountryCode(java.lang.String countryCode) {
        this.countryCode = countryCode;
    }
}
