// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.wheatherreport.proxy;


public class GetGeoIPContextResponse {
    protected com.wheatherreport.proxy.GeoIP getGeoIPContextResult;
    
    public GetGeoIPContextResponse() {
    }
    
    public GetGeoIPContextResponse(com.wheatherreport.proxy.GeoIP getGeoIPContextResult) {
        this.getGeoIPContextResult = getGeoIPContextResult;
    }
    
    public com.wheatherreport.proxy.GeoIP getGetGeoIPContextResult() {
        return getGeoIPContextResult;
    }
    
    public void setGetGeoIPContextResult(com.wheatherreport.proxy.GeoIP getGeoIPContextResult) {
        this.getGeoIPContextResult = getGeoIPContextResult;
    }
}
