// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.wheatherreport.proxy;


public class GetGeoIPResponse {
    protected com.wheatherreport.proxy.GeoIP getGeoIPResult;
    
    public GetGeoIPResponse() {
    }
    
    public GetGeoIPResponse(com.wheatherreport.proxy.GeoIP getGeoIPResult) {
        this.getGeoIPResult = getGeoIPResult;
    }
    
    public com.wheatherreport.proxy.GeoIP getGetGeoIPResult() {
        return getGeoIPResult;
    }
    
    public void setGetGeoIPResult(com.wheatherreport.proxy.GeoIP getGeoIPResult) {
        this.getGeoIPResult = getGeoIPResult;
    }
}
