// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.wheatherreport.proxy;


public class GetGeoIP {
    protected java.lang.String IPAddress;
    
    public GetGeoIP() {
    }
    
    public GetGeoIP(java.lang.String IPAddress) {
        this.IPAddress = IPAddress;
    }
    
    public java.lang.String getIPAddress() {
        return IPAddress;
    }
    
    public void setIPAddress(java.lang.String IPAddress) {
        this.IPAddress = IPAddress;
    }
}
