// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.jaxrpc.client;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class Hello_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public Hello_Tie() throws Exception {
        super(new com.jaxrpc.client.HelloServices_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: sayhello
     */
    private void invoke_sayhello(StreamingHandlerState state) throws Exception {
        
        com.jaxrpc.client.Hello_sayhello_RequestStruct myHello_sayhello_RequestStruct = null;
        Object myHello_sayhello_RequestStructObj =
            state.getRequest().getBody().getValue();
        
        if (myHello_sayhello_RequestStructObj instanceof SOAPDeserializationState) {
            myHello_sayhello_RequestStruct = (com.jaxrpc.client.Hello_sayhello_RequestStruct)((SOAPDeserializationState)myHello_sayhello_RequestStructObj).getInstance();
        } else {
            myHello_sayhello_RequestStruct = (com.jaxrpc.client.Hello_sayhello_RequestStruct)myHello_sayhello_RequestStructObj;
        }
        
        try {
            java.lang.String sayhelloreturns = 
                ((com.jaxrpc.client.Hello) getTarget()).sayhello(myHello_sayhello_RequestStruct.getName());
            com.jaxrpc.client.Hello_sayhello_ResponseStruct myHello_sayhello_ResponseStruct =
                new com.jaxrpc.client.Hello_sayhello_ResponseStruct();
            SOAPHeaderBlockInfo headerInfo;
            myHello_sayhello_ResponseStruct.setSayhelloreturns(sayhelloreturns);
            
            SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_sayhello_sayhelloResponse_QNAME);
            bodyBlock.setValue(myHello_sayhello_ResponseStruct);
            bodyBlock.setSerializer(ns1_myHello_sayhello_ResponseStruct_SOAPSerializer);
            state.getResponse().setBody(bodyBlock);
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_sayhello_sayhello_QNAME)) {
            state.getRequest().setOperationCode(sayhello_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case sayhello_OPCODE:
                deserialize_sayhello(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the sayhello operation.
     */
    private void deserialize_sayhello(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        java.lang.Object myHello_sayhello_RequestStructObj =
            ns1_myHello_sayhello_RequestStruct_SOAPSerializer.deserialize(ns1_sayhello_sayhello_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_sayhello_sayhello_QNAME);
        bodyBlock.setValue(myHello_sayhello_RequestStructObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case sayhello_OPCODE:
                invoke_sayhello(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", java.lang.Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    public java.lang.String getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_sayhello_sayhello_QNAME)) {
            return sayhello_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case sayhello_OPCODE:
                {
                    Class[] carray = { java.lang.String.class };
                    theMethod = (com.jaxrpc.client.Hello.class).getMethod("sayhello", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[1];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 1 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myHello_sayhello_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.jaxrpc.client.Hello_sayhello_RequestStruct.class, ns1_sayhello_TYPE_QNAME);
        ns1_myHello_sayhello_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.jaxrpc.client.Hello_sayhello_ResponseStruct.class, ns1_sayhelloResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName portName = new QName("http://client.jaxrpc.com", "helloSOAPPort");
    private static final int sayhello_OPCODE = 0;
    private static final javax.xml.namespace.QName ns1_sayhello_sayhello_QNAME = new QName("http://client.jaxrpc.com", "sayhello");
    private static final javax.xml.namespace.QName ns1_sayhello_TYPE_QNAME = new QName("http://client.jaxrpc.com", "sayhello");
    private CombinedSerializer ns1_myHello_sayhello_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_sayhello_sayhelloResponse_QNAME = new QName("http://client.jaxrpc.com", "sayhelloResponse");
    private static final javax.xml.namespace.QName ns1_sayhelloResponse_TYPE_QNAME = new QName("http://client.jaxrpc.com", "sayhelloResponse");
    private CombinedSerializer ns1_myHello_sayhello_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://client.jaxrpc.com"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
