// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.jaxrpc.client;


public class Hello_sayhello_RequestStruct {
    protected java.lang.String name;
    
    public Hello_sayhello_RequestStruct() {
    }
    
    public Hello_sayhello_RequestStruct(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
