// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.jaxrpc.client;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Hello_sayhello_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.jaxrpc.client.Hello_sayhello_RequestStruct _instance;
    private java.lang.String name;
    private static final int myNAME_INDEX = 0;
    
    public Hello_sayhello_RequestStruct_SOAPBuilder() {
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myNAME_INDEX:
                    _instance.setName((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.jaxrpc.client.Hello_sayhello_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
