// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.jaxrpc.client;

public interface Hello extends java.rmi.Remote {
    public java.lang.String sayhello(java.lang.String name) throws 
         java.rmi.RemoteException;
}
