// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.jaxrpc.client;


public class Hello_sayhello_ResponseStruct {
    protected java.lang.String sayhelloreturns;
    
    public Hello_sayhello_ResponseStruct() {
    }
    
    public Hello_sayhello_ResponseStruct(java.lang.String sayhelloreturns) {
        this.sayhelloreturns = sayhelloreturns;
    }
    
    public java.lang.String getSayhelloreturns() {
        return sayhelloreturns;
    }
    
    public void setSayhelloreturns(java.lang.String sayhelloreturns) {
        this.sayhelloreturns = sayhelloreturns;
    }
}
